name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build verbose
      uses: actions-rs/cargo@v1.0.1
      with:
        command: build
        args: --verbose

    - name: Run tests
      uses: actions-rs/cargo@v1.0.1
      with:
        command: test
        args: --verbose
        

    - name: Generate docs
      uses: actions-rs/cargo@v1.0.1
      with:
        command: doc
        args: --no-deps --verbose        
        
    - name: Archive docs
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: target/doc      


    - name: Coverage (lcov)
      uses: Swatinem/fucov@v1.0.0    
      
    - name: Coverage (html)
      uses: Swatinem/fucov@v1.0.0
      with:
        output-format: html
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3.1.0
      with: 
        fail_ci_if_error: true
        verbose: true
      
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage
